@host=http://localhost:3000

###
GET {{host}}/coffees/abc HTTP/1.1
Authorization: 1234567890

###
GET {{host}}/coffees/flavours HTTP/1.1
Authorization: 1234567890

###
POST {{host}}/coffees
Content-Type: application/json
Authorization: 1234567890

{
  "name": "Espresso",
  "brand": "Italian Roast",
  "flavours": [
    {"name": "Chocolate2"},
    {"name": "Vanilla2"}
  ]
}